version: '2'

services:
  data:
    image: busybox:latest
    volumes:
      - ./../book24_transactions/:/var/www/book24_transactions
      - ./docker/log:/var/log/container

  nginx:
    container_name: book24_nginx
    image: nginx:latest
    ports:
      - "8010:80" # API
    volumes_from:
      - php
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/log:/var/log/container
    links:
      - php:fpm
    depends_on:
      - php
    logging:
      driver: json-file
      options:
        max-size: "16m"
        max-file: "10"
    networks:
      book24net:
        ipv4_address: 192.168.12.10

  db:
    container_name: book24_mysql
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book24
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      book24net:
        ipv4_address: 192.168.12.11

  php:
    container_name: book24_php
    build: docker/php
    working_dir: /var/www
    volumes_from:
      - data
    logging:
      driver: json-file
      options:
        max-size: "32m"
        max-file: "10"
    networks:
      book24net:
        ipv4_address: 192.168.12.12

  phpmyadmin:
    container_name: book24_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8011:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      book24net:
        ipv4_address: 192.168.12.13

networks:
  book24net:
    external: true